general {
    inhibit_sleep = 0
}


listener {
    timeout = 1200                            # in seconds.
    on-timeout = hyprlock
    on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}
